spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/fourddata;MODE=MSSQLServer
    driver-class-name: org.h2.Driver
    username: sa
    password:
    idle-timeout: 60000
    maximum-pool-size: 50
    minimum-idle: 5
    connection-test-query: SELECT 1
    validation-timeout: 500
    register-mbeans: true
  h2:
    console:
      enabled: true
      path: /db
server:
  port: 8888

graphql:
  spqr:
    gui:
      enabled: true